/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.keyko.monitoring.schemas;
@org.apache.avro.specific.AvroGenerated
public enum AlertEventStatus implements org.apache.avro.generic.GenericEnumSymbol<AlertEventStatus> {
  FATAL, ERROR, WARNING, INFO, DEBUG  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertEventStatus\",\"namespace\":\"io.keyko.monitoring.schemas\",\"symbols\":[\"FATAL\",\"ERROR\",\"WARNING\",\"INFO\",\"DEBUG\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
