/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.keyko.monitoring.schemas;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class BlockEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7285302814443941338L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BlockEvent\",\"namespace\":\"io.keyko.monitoring.schemas\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"details\",\"type\":{\"type\":\"record\",\"name\":\"BlockDetails\",\"fields\":[{\"name\":\"number\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"java-class\":\"java.math.BigInteger\"},{\"name\":\"hash\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"java-class\":\"java.math.BigInteger\"},{\"name\":\"nodeName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"retries\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BlockEvent> ENCODER =
      new BinaryMessageEncoder<BlockEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BlockEvent> DECODER =
      new BinaryMessageDecoder<BlockEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BlockEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BlockEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BlockEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BlockEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BlockEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BlockEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BlockEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BlockEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public String id;
  @Deprecated public String type;
  @Deprecated public io.keyko.monitoring.schemas.BlockDetails details;
  @Deprecated public int retries;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BlockEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param type The new value for type
   * @param details The new value for details
   * @param retries The new value for retries
   */
  public BlockEvent(String id, String type, io.keyko.monitoring.schemas.BlockDetails details, Integer retries) {
    this.id = id;
    this.type = type;
    this.details = details;
    this.retries = retries;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return details;
    case 3: return retries;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (String)value$; break;
    case 1: type = (String)value$; break;
    case 2: details = (io.keyko.monitoring.schemas.BlockDetails)value$; break;
    case 3: retries = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'details' field.
   * @return The value of the 'details' field.
   */
  public io.keyko.monitoring.schemas.BlockDetails getDetails() {
    return details;
  }


  /**
   * Sets the value of the 'details' field.
   * @param value the value to set.
   */
  public void setDetails(io.keyko.monitoring.schemas.BlockDetails value) {
    this.details = value;
  }

  /**
   * Gets the value of the 'retries' field.
   * @return The value of the 'retries' field.
   */
  public int getRetries() {
    return retries;
  }


  /**
   * Sets the value of the 'retries' field.
   * @param value the value to set.
   */
  public void setRetries(int value) {
    this.retries = value;
  }

  /**
   * Creates a new BlockEvent RecordBuilder.
   * @return A new BlockEvent RecordBuilder
   */
  public static io.keyko.monitoring.schemas.BlockEvent.Builder newBuilder() {
    return new io.keyko.monitoring.schemas.BlockEvent.Builder();
  }

  /**
   * Creates a new BlockEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BlockEvent RecordBuilder
   */
  public static io.keyko.monitoring.schemas.BlockEvent.Builder newBuilder(io.keyko.monitoring.schemas.BlockEvent.Builder other) {
    if (other == null) {
      return new io.keyko.monitoring.schemas.BlockEvent.Builder();
    } else {
      return new io.keyko.monitoring.schemas.BlockEvent.Builder(other);
    }
  }

  /**
   * Creates a new BlockEvent RecordBuilder by copying an existing BlockEvent instance.
   * @param other The existing instance to copy.
   * @return A new BlockEvent RecordBuilder
   */
  public static io.keyko.monitoring.schemas.BlockEvent.Builder newBuilder(io.keyko.monitoring.schemas.BlockEvent other) {
    if (other == null) {
      return new io.keyko.monitoring.schemas.BlockEvent.Builder();
    } else {
      return new io.keyko.monitoring.schemas.BlockEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BlockEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BlockEvent>
    implements org.apache.avro.data.RecordBuilder<BlockEvent> {

    private String id;
    private String type;
    private io.keyko.monitoring.schemas.BlockDetails details;
    private io.keyko.monitoring.schemas.BlockDetails.Builder detailsBuilder;
    private int retries;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.keyko.monitoring.schemas.BlockEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.details)) {
        this.details = data().deepCopy(fields()[2].schema(), other.details);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasDetailsBuilder()) {
        this.detailsBuilder = io.keyko.monitoring.schemas.BlockDetails.newBuilder(other.getDetailsBuilder());
      }
      if (isValidValue(fields()[3], other.retries)) {
        this.retries = data().deepCopy(fields()[3].schema(), other.retries);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing BlockEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(io.keyko.monitoring.schemas.BlockEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.details)) {
        this.details = data().deepCopy(fields()[2].schema(), other.details);
        fieldSetFlags()[2] = true;
      }
      this.detailsBuilder = null;
      if (isValidValue(fields()[3], other.retries)) {
        this.retries = data().deepCopy(fields()[3].schema(), other.retries);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder setId(String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder setType(String value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'details' field.
      * @return The value.
      */
    public io.keyko.monitoring.schemas.BlockDetails getDetails() {
      return details;
    }


    /**
      * Sets the value of the 'details' field.
      * @param value The value of 'details'.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder setDetails(io.keyko.monitoring.schemas.BlockDetails value) {
      validate(fields()[2], value);
      this.detailsBuilder = null;
      this.details = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'details' field has been set.
      * @return True if the 'details' field has been set, false otherwise.
      */
    public boolean hasDetails() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'details' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.keyko.monitoring.schemas.BlockDetails.Builder getDetailsBuilder() {
      if (detailsBuilder == null) {
        if (hasDetails()) {
          setDetailsBuilder(io.keyko.monitoring.schemas.BlockDetails.newBuilder(details));
        } else {
          setDetailsBuilder(io.keyko.monitoring.schemas.BlockDetails.newBuilder());
        }
      }
      return detailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'details' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.keyko.monitoring.schemas.BlockEvent.Builder setDetailsBuilder(io.keyko.monitoring.schemas.BlockDetails.Builder value) {
      clearDetails();
      detailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'details' field has an active Builder instance
     * @return True if the 'details' field has an active Builder instance
     */
    public boolean hasDetailsBuilder() {
      return detailsBuilder != null;
    }

    /**
      * Clears the value of the 'details' field.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder clearDetails() {
      details = null;
      detailsBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'retries' field.
      * @return The value.
      */
    public int getRetries() {
      return retries;
    }


    /**
      * Sets the value of the 'retries' field.
      * @param value The value of 'retries'.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder setRetries(int value) {
      validate(fields()[3], value);
      this.retries = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'retries' field has been set.
      * @return True if the 'retries' field has been set, false otherwise.
      */
    public boolean hasRetries() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'retries' field.
      * @return This builder.
      */
    public io.keyko.monitoring.schemas.BlockEvent.Builder clearRetries() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BlockEvent build() {
      try {
        BlockEvent record = new BlockEvent();
        record.id = fieldSetFlags()[0] ? this.id : (String) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (String) defaultValue(fields()[1]);
        if (detailsBuilder != null) {
          try {
            record.details = this.detailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("details"));
            throw e;
          }
        } else {
          record.details = fieldSetFlags()[2] ? this.details : (io.keyko.monitoring.schemas.BlockDetails) defaultValue(fields()[2]);
        }
        record.retries = fieldSetFlags()[3] ? this.retries : (Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BlockEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BlockEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BlockEvent>
    READER$ = (org.apache.avro.io.DatumReader<BlockEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.type);

    this.details.customEncode(out);

    out.writeInt(this.retries);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.type = in.readString();

      if (this.details == null) {
        this.details = new io.keyko.monitoring.schemas.BlockDetails();
      }
      this.details.customDecode(in);

      this.retries = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.type = in.readString();
          break;

        case 2:
          if (this.details == null) {
            this.details = new io.keyko.monitoring.schemas.BlockDetails();
          }
          this.details.customDecode(in);
          break;

        case 3:
          this.retries = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










