/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.keyko.monitoring.schemas;
@org.apache.avro.specific.AvroGenerated
public enum TransactionStatus implements org.apache.avro.generic.GenericEnumSymbol<TransactionStatus> {
  UNCONFIRMED, CONFIRMED, INVALIDATED, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionStatus\",\"namespace\":\"io.keyko.monitoring.schemas\",\"symbols\":[\"UNCONFIRMED\",\"CONFIRMED\",\"INVALIDATED\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
