package io.keyko.monitoring.stream;

import io.keyko.monitoring.schemas.*;
import org.apache.kafka.common.serialization.Serde;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.kstream.Joined;
import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.KTable;
import org.apache.kafka.streams.kstream.Produced;


public class EventProcessor {

  /**
   * Filter the events that has been already confirmed.
   *
   * @param contractEvents KStream with the event from the topic contract-events generated by Eventeum
   * @return KStream with the events that have been confirmed.
   */
  public KStream<String, EventRecord> filterConfirmed(KStream<String, EventRecord> contractEvents) {
    return contractEvents
      .filter((key, event) -> event.getDetails().getStatus().toString().equalsIgnoreCase("CONFIRMED"));
  }

  /**
   * Sending confirmed events to a topic corresponding with the name of the event.
   *
   * @param confirmedEvents Stream with the confirmed events
   */
  public void splitEventTopics(KStream<String, EventBlockRecord> confirmedEvents, Serde<EventBlockRecord> eventBlockAvroSerde) {
    confirmedEvents.to((key, value, recordContext) ->
        value.getDetails().getName().toLowerCase(),
      Produced.with(Serdes.String(), eventBlockAvroSerde)
    );
  }

  /**
   * Sending confirmed events to a topic corresponding with the name of the event.
   *
   * @param confirmedEvents Stream with the confirmed events
   */
  public void splitViewTopics(KStream<String, ViewBlockRecord> confirmedEvents, Serde<ViewBlockRecord> viewBlockAvroSerde) {
    confirmedEvents.to((key, value, recordContext) ->
        value.getDetails().getName().toLowerCase(),
      Produced.with(Serdes.String(), viewBlockAvroSerde)
    );
  }

  /**
   * Join the events with the corresponding block to track the timestamp of mining.
   *
   * @param eventAvroStream Stream with the confirmed events
   * @param blockAvroStream Table with the blocks
   * @param eventAvroSerde  Event avro serde
   * @param blockAvroSerde  Block avro serde
   * @return KStream
   */
  public KStream<String, EventBlockRecord> joinEventWithBlock(KStream<String, EventRecord> eventAvroStream, KTable<String, BlockRecord> blockAvroStream,
                                                        Serde<EventRecord> eventAvroSerde, Serde<BlockRecord> blockAvroSerde) {
    return eventAvroStream
      .selectKey((key, event) -> event.getDetails().getBlockHash())
      .join(blockAvroStream,
        (event, block) -> {
          EventBlockRecord eventblock = new EventBlockRecord();

          eventblock.setDetails(event.getDetails());
          eventblock.setDetailsBlock(block.getDetails());
          eventblock.setId(event.getId());
          eventblock.setRetries(event.getRetries());
          eventblock.setType(event.getType());

          return eventblock;
        },
        Joined.with(Serdes.String(), eventAvroSerde, blockAvroSerde)
      )
      .selectKey((key, event) -> event.getId());
  }


  /**
   * Join the views with the corresponding block to track the timestamp of mining.
   *
   * @param viewAvroStream  Stream with the confirmed views
   * @param blockAvroStream Table with the blocks
   * @param viewAvroSerde   View avro serde
   * @param blockAvroSerde  Block avro serde
   * @return KStream
   */
  public KStream<String, ViewBlockRecord> joinViewWithBlock(KStream<String, ViewRecord> viewAvroStream, KTable<String, BlockRecord> blockAvroStream,
                                                      Serde<ViewRecord> viewAvroSerde, Serde<BlockRecord> blockAvroSerde) {
    return viewAvroStream
      .selectKey((key, view) -> view.getDetails().getBlockHash())
      .join(blockAvroStream,
        (view, block) -> {
          ViewBlockRecord viewBlock = new ViewBlockRecord();

          viewBlock.setDetails(view.getDetails());
          viewBlock.setDetailsBlock(block.getDetails());
          viewBlock.setId(view.getId());
          viewBlock.setRetries(view.getRetries());
          viewBlock.setType(view.getType());
          return viewBlock;
        },
        Joined.with(Serdes.String(), viewAvroSerde, blockAvroSerde)
      )
      .selectKey((key, view) -> view.getId())
      ;

  }

}
